name: Build Packages

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Kiwix
        run: |
          git clone --single-branch --branch main https://github.com/Jgigantino31/Kiwix.git
          cd Kiwix
          docker build . --tag ghcr.io/jgigantino31/kiwix:latest
          docker push ghcr.io/jgigantino31/kiwix:latest
